# Generated by Django 2.2.19 on 2022-09-25 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientsvolume',
            name='volume',
            field=models.PositiveIntegerField(verbose_name='Количество'),
        ),
    ]
