# Generated by Django 2.2.19 on 2022-09-22 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='color',
            field=models.CharField(max_length=16, unique=True, verbose_name='Цветовой HEX-код'),
        ),
    ]
