# Generated by Django 2.2.19 on 2022-09-27 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='ingredients',
            field=models.ManyToManyField(related_name='recipes', to='ingredients.IngredientsAmount', verbose_name='Список ингридиентов'),
        ),
    ]
